development:
  adapter: postgresql
  encoding: unicode
  database: wigo_development
  pool: 5
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: wigo_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: wigo_production
  pool: 5
